# -*- coding: utf-8 -*-
"""Supplier Risk github.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1mW5MkL3CaJYbUXYRz8RWU01LIhtw0hor

### `Load the CSV file into a DataFrame`
"""

import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns


from google.colab import drive
drive.mount('/content/drive')


# Load the CSV file into a DataFrame
# 手動掛接訓練CSV檔案
# df = pd.read_csv('/content/Data_中英欄位.csv')

df = pd.read_csv('/content/drive/MyDrive/Data_中英欄位.csv')
# df = pd.read_csv('/content/drive/MyDrive/Data_中英欄位_simplified.csv')
# df
display(df.shape)

# print("Displaying the first 10 rows of 'df' to verify column names:")
# display(df.head(10))

"""### 選取特徵X與目標變數Y 切分訓練/測試資料集"""

from sklearn.model_selection import train_test_split
import pandas as pd

# Define the target variable y
y = df['Supplier Risk（供應商風險等級）']


# Define the features X with only 'Supplier ESG Score（供應商ESG評分）' and 'PO Status（採購單狀態）'
X_selected = df[[
        'Supplier Tier（供應商層級）',
        'Maverick Spend（脫軌採購）',
        'Preferred Supplier（優先供應商）',
        'Days Late（延誤天數）',

        # bad feature importance
        'On Time Delivery（是否準時交貨）',
        'Invoice Status（發票狀態）',
        'Payment Status（付款狀態）',
        'Single Source Flag（單一來源標記）',
        'PO Type（採購單類型）',
        'Contract Type（合約類型）',
        'PO Status（採購單狀態）',

        # strong data leakage
        # 'Supplier ESG Score（供應商ESG評分）', # Removed due to strong data leakage with target variable
        ]]


# Handle categorical features in X_selected by one-hot encoding 'PO Status（採購單狀態）'
categorical_cols_selected = X_selected.select_dtypes(include='object').columns

if not categorical_cols_selected.empty:
    print(f"對以下類別特徵進行獨熱編碼: {list(categorical_cols_selected)}")
    X_selected = pd.get_dummies(X_selected, columns=categorical_cols_selected, drop_first=True)
else:
    print("沒有找到需要進行獨熱編碼的類別特徵。")

# Perform the train-test split (70% training, 30% testing)
# Using stratify=y to maintain the proportion of 'Supplier Risk' classes in both sets
X_train_selected, X_test_selected, y_train_selected, y_test_selected = train_test_split(
    X_selected, y, test_size=0.3, random_state=1, stratify=y
)

print(f"\n選取特徵後的 X 形狀: {X_selected.shape}")
print(f"目標變數 y 形狀: {y.shape}")

print(f"\n訓練特徵集 (X_train_selected) 形狀: {X_train_selected.shape}")
print(f"測試特徵集 (X_test_selected) 形狀: {X_test_selected.shape}")

print(f"訓練目標變數 (y_train_selected) 形狀: {y_train_selected.shape}")
print(f"測試目標變數 (y_test_selected) 形狀: {y_test_selected.shape}")

"""## 使用 `X_selected` 特徵縮放 (Feature Scaling) Standardization and Normalization"""

from sklearn.preprocessing import StandardScaler, MinMaxScaler
import pandas as pd


print("標準化和正規化前的訓練集形狀: ", X_train_selected.shape)
print("標準化和正規化前的測試集形狀: ", X_test_selected.shape)


print("--- 開始進行特徵標準化和正規化 ---")
# 1. 特徵標準化 (Standardization)
# 使用 StandardScaler 將特徵縮放到均值為0，標準差為1。
print("開始進行特徵標準化 (X_selected)...")
scaler_selected = StandardScaler()
X_train_selected_scaled = scaler_selected.fit_transform(X_train_selected)
X_test_selected_scaled = scaler_selected.transform(X_test_selected)

X_train_selected_std = scaler_selected.fit_transform(X_train_selected)
X_test_selected_std = scaler_selected.transform(X_test_selected)
print("特徵標準化完成。")




# 2. 特徵正規化 (Normalization)
# 在標準化後的數據上應用 MinMaxScaler，將數據縮放到0到1的範圍。
print("\n開始進行特徵正規化 (X_selected_std)...")
normalizer_selected = MinMaxScaler()
# X_train_selected_normalized = normalizer_selected.fit_transform(X_train_selected_scaled)
# X_test_selected_normalized = normalizer_selected.transform(X_test_selected_scaled)
X_train_selected_normalized = normalizer_selected.fit_transform(X_train_selected_std)
X_test_selected_normalized = normalizer_selected.transform(X_test_selected_std)
print("特徵正規化完成。")

print("標準化和正規化後的訓練集形狀: ", X_train_selected_normalized.shape)
print("標準化和正規化後的測試集形狀: ", X_test_selected_normalized.shape)

"""### 檢查標準化及正規化後的數據"""

import pandas as pd

print("--- 檢查標準化後的數據 (X_train_selected_std) ---")
display(pd.DataFrame(X_train_selected_std, columns=X_train_selected.columns).describe())

print("\n--- 檢查標準化後的數據 (X_test_selected_std) ---")
display(pd.DataFrame(X_test_selected_std, columns=X_test_selected.columns).describe())

print("\n--- 檢查正規化後的數據 (X_train_selected_normalized) ---")
display(pd.DataFrame(X_train_selected_normalized, columns=X_train_selected.columns).describe())

print("\n--- 檢查正規化後的數據 (X_test_selected_normalized) ---")
display(pd.DataFrame(X_test_selected_normalized, columns=X_test_selected.columns).describe())

'''
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix, ConfusionMatrixDisplay
# from sklearn.preprocessing import StandardScaler
from sklearn.preprocessing import MinMaxScaler, StandardScaler
import matplotlib.pyplot as plt

# 1. 特徵縮放 (Feature Scaling)
# Logistic Regression 對於未縮放的特徵比較敏感。
print("開始進行特徵標準化 (X_selected)...")
scaler_selected = StandardScaler()
X_train_selected_scaled = scaler_selected.fit_transform(X_train_selected)
X_test_selected_scaled = scaler_selected.transform(X_test_selected)
print("特徵標準化完成。")
'''

'''
# 2. 初始化邏輯回歸模型
#   - max_iter: 增加迭代次數以確保模型收斂，避免 ConvergenceWarning。
#   - class_weight='balanced': 自動調整類別權重，以應對類別不平衡問題。
model_selected = LogisticRegression(max_iter=5000, random_state=42, class_weight='balanced')

# 3. 訓練模型
print("\n開始訓練 Logistic Regression 模型 (使用 X_selected)...")
model_selected.fit(X_train_selected_scaled, y_train_selected)
print("模型訓練完成。")

# 4. 進行預測
y_pred_selected = model_selected.predict(X_test_selected_scaled)

# 5. 評估模型性能
print("\n--- 模型評估 (使用 X_selected) ---")

# 準確度
accuracy_selected = accuracy_score(y_test_selected, y_pred_selected)
print(f"準確度 (Accuracy): {accuracy_selected:.4f}")

# 分類報告 (包含精確度、召回率、F1-score)
print("\n分類報告 (Classification Report):\n")
print(classification_report(y_test_selected, y_pred_selected))

# 混淆矩陣
print("\n混淆矩陣 (Confusion Matrix):\n")
cm_selected = confusion_matrix(y_test_selected, y_pred_selected, labels=model_selected.classes_)
display_cm_selected = ConfusionMatrixDisplay(confusion_matrix=cm_selected, display_labels=model_selected.classes_)
display_cm_selected.plot(cmap=plt.cm.Blues)
plt.title('Confusion Matrix for Logistic Regression (X_selected)')
plt.show()
'''

'''
from sklearn.preprocessing import MinMaxScaler, StandardScaler
import pandas as pd

# Function for Min-Max Normalization
def min_max_normalize(series):
    if series.empty or series.nunique() == 1:
        return series # Return original if empty or only one unique value
    scaler = MinMaxScaler()
    return pd.Series(scaler.fit_transform(series.values.reshape(-1, 1)).flatten(), index=series.index)

# Function for Z-score Standardization
def z_score_standardize(series):
    if series.empty or series.std() == 0:
        return series # Return original if empty or standard deviation is zero
    scaler = StandardScaler()
    return pd.Series(scaler.fit_transform(series.values.reshape(-1, 1)).flatten(), index=series.index)

print("Min-Max Normalization and Z-score Standardization functions are now available.")
'''

'''
from sklearn.preprocessing import MinMaxScaler, StandardScaler
import pandas as pd

# Assuming 'df' DataFrame is already loaded and available from previous cells.
# If not, please ensure the cell loading the DataFrame (e.g., cell a17dce57) is executed first.

# Define normalization and standardization functions
# Function for Min-Max Normalization
def min_max_normalize(series):
    if series.empty or series.nunique() == 1:
        return series # Return original if empty or only one unique value
    scaler = MinMaxScaler()
    return pd.Series(scaler.fit_transform(series.values.reshape(-1, 1)).flatten(), index=series.index)

# Function for Z-score Standardization
def z_score_standardize(series):
    if series.empty or series.std() == 0:
        return series # Return original if empty or standard deviation is zero
    scaler = StandardScaler()
    return pd.Series(scaler.fit_transform(series.values.reshape(-1, 1)).flatten(), index=series.index)




print("--- Processing 'Supplier ESG Score（供應商ESG評分）' ---")
df['Supplier ESG Score_Normalized'] = min_max_normalize(df['Supplier ESG Score（供應商ESG評分）'])
df['Supplier ESG Score_Standardized'] = z_score_standardize(df['Supplier ESG Score（供應商ESG評分）'])
display(df[['Supplier ESG Score（供應商ESG評分）', 'Supplier ESG Score_Normalized', 'Supplier ESG Score_Standardized']].head())



print("\n--- Processing 'Days Late（延誤天數）' ---")
df['Days Late_Normalized'] = min_max_normalize(df['Days Late（延誤天數）'])
df['Days Late_Standardized'] = z_score_standardize(df['Days Late（延誤天數）'])
display(df[['Days Late（延誤天數）', 'Days Late_Normalized', 'Days Late_Standardized']].head())



print("\n--- Processing 'On Time Delivery（是否準時交貨）' ---")
# Convert binary categorical to numerical (0/1)
df['On Time Delivery_Encoded'] = df['On Time Delivery（是否準時交貨）'].map({'Yes': 1, 'No': 0})

# Apply normalization and standardization to the encoded column
df['On Time Delivery_Normalized'] = min_max_normalize(df['On Time Delivery_Encoded'])
df['On Time Delivery_Standardized'] = z_score_standardize(df['On Time Delivery_Encoded'])
display(df[['On Time Delivery（是否準時交貨）', 'On Time Delivery_Encoded', 'On Time Delivery_Normalized', 'On Time Delivery_Standardized']].head())

# Example usage: Normalize 'Unit Price（單價）' column
df['Unit Price_Normalized'] = min_max_normalize(df['Unit Price（單價）'])
display(df[['Unit Price（單價）', 'Unit Price_Normalized']].head())

# Example usage: Standardize 'Quantity（數量）' column
df['Quantity_Standardized'] = z_score_standardize(df['Quantity（數量）'])
display(df[['Quantity（數量）', 'Quantity_Standardized']].head())



print("\n--- Processing 'PO Status（採購單狀態）' (One-Hot Encoding) ---")
df = pd.concat([df, pd.get_dummies(df['PO Status（採購單狀態）'], prefix='PO Status')], axis=1)
display(df[[col for col in df.columns if 'PO Status' in col]].head())



print("\n--- Processing 'Invoice Status（發票狀態）' (One-Hot Encoding) ---")
df = pd.concat([df, pd.get_dummies(df['Invoice Status（發票狀態）'], prefix='Invoice Status')], axis=1)
display(df[[col for col in df.columns if 'Invoice Status' in col]].head())



print("\n--- Processing 'Payment Status（付款狀態）' (One-Hot Encoding) ---")
df = pd.concat([df, pd.get_dummies(df['Payment Status（付款狀態）'], prefix='Payment Status')], axis=1)
display(df[[col for col in df.columns if 'Payment Status' in col]].head())
'''

"""## 檢查類別不平衡 (Imbalanced Data) 並進行重複取樣 SMOTE（Synthetic Minority Over-sampling Technique，合成少數類別過採樣技術"""

print('--- 檢查類別不平衡 (Imbalanced Data) 並進行重複取樣 ---')

import pandas as pd
from collections import Counter
from imblearn.over_sampling import SMOTE
import matplotlib.pyplot as plt
import seaborn as sns

# 假設 X_train_selected_scaled 和 y_train_selected 已經在之前的單元格中定義。
# 如果尚未定義，請確保執行了特徵選擇和標準化的單元格。

print("原始訓練資料 (y_train_selected) 的類別分佈:")
original_counts = Counter(y_train_selected)
print(original_counts)

# 視覺化原始類別分佈
plt.figure(figsize=(8, 6))
sns.barplot(x=list(original_counts.keys()), y=list(original_counts.values()), palette='viridis')
plt.title('Original Training Data Class Distribution')
plt.xlabel('Supplier Risk Level')
plt.ylabel('Count')
plt.show()

# 初始化 SMOTE
# random_state 確保結果的可重現性
smote = SMOTE(random_state=42)

# 對訓練資料進行過採樣
X_train_resampled, y_train_resampled = smote.fit_resample(X_train_selected_scaled, y_train_selected)

print("\n過採樣後訓練資料的類別分佈:")
resampled_counts = Counter(y_train_resampled)
print(resampled_counts)

# 視覺化過採樣後類別分佈
plt.figure(figsize=(8, 6))
sns.barplot(x=list(resampled_counts.keys()), y=list(resampled_counts.values()), palette='viridis')
plt.title('Resampled Training Data Class Distribution (SMOTE)')
plt.xlabel('Supplier Risk Level')
plt.ylabel('Count')
plt.show()

print("\nSMOTE 過採樣完成。")
print(f"X_train_resampled 的形狀: {X_train_resampled.shape}")
print(f"y_train_resampled 的形狀: {y_train_resampled.shape}")

"""## 多類別分類模型（Multi-class Classification Model) 評估

### 隨機森林模型 (RandomForestClassifier)
"""

# 使用隨機森林
from sklearn.ensemble import RandomForestClassifier

'''
# 初始化隨機森林模型
# rf_model = RandomForestClassifier(n_estimators=100, random_state=42, class_weight='balanced')
'''

# 建議調優參數組合
rf_model = RandomForestClassifier(
    n_estimators=200,      # 增加樹的數量，提升穩定性
    max_depth=10,          # 限制樹的深度，防止過度擬合 (可嘗試 5~15)
    min_samples_split=5,   # 節點分割所需的最小樣本數
    class_weight='balanced_subsample', # 比 'balanced' 更適合隨機森林的抽樣特性
    random_state=42
)
model_selected = rf_model


# 訓練
# rf_model.fit(X_train_selected_scaled, y_train_selected)
rf_model.fit(X_train_resampled, y_train_resampled)

# 預測與評估
y_pred_selected = rf_model.predict(X_test_selected_scaled)
y_pred_selected_rf = y_pred_selected

"""### 邏輯回歸模型 (LogisticRegression)"""

from sklearn.linear_model import LogisticRegression

# 2. 初始化邏輯回歸模型
#   - max_iter: 增加迭代次數以確保模型收斂，避免 ConvergenceWarning。
#   - class_weight='balanced': 自動調整類別權重，以應對類別不平衡問題。
lr_model = LogisticRegression(max_iter=5000, random_state=42, class_weight='balanced')
model_selected= lr_model


# 3. 訓練模型
print("\n開始訓練 Logistic Regression 模型 (使用 X_selected)...")
lr_model.fit(X_train_selected_scaled, y_train_selected)
print("模型訓練完成。")

# 4. 進行預測
print("\n開始進行預測 (使用 X_selected)...")
y_pred_selected = lr_model.predict(X_test_selected_scaled)
y_pred_selected_lr = y_pred_selected

"""### 支持向量機 （SVM）"""

from sklearn.svm import SVC
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix, ConfusionMatrixDisplay
import matplotlib.pyplot as plt
from imblearn.over_sampling import SMOTE
from collections import Counter

print("\n--- Support Vector Machine (SVM) Model ---")

# Check if resampled data is available; if not, re-run SMOTE
if 'X_train_resampled' not in locals() or 'y_train_resampled' not in locals():
    print("\nWarning: X_train_resampled or y_train_resampled not found. Attempting to re-run SMOTE oversampling...")

    # Check if the necessary scaled and split data are available
    if 'X_train_selected_scaled' not in locals() or 'y_train_selected' not in locals() or \
       'X_test_selected_scaled' not in locals() or 'y_test_selected' not in locals():
        print("\nError: Required variables 'X_train_selected_scaled', 'y_train_selected', 'X_test_selected_scaled', or 'y_test_selected' are not defined.")
        print("Please ensure that the data splitting (cell cWwQ2XAf5V-K) and feature scaling (cell 32eb669e) cells have been executed successfully.")
        raise NameError("Required data for SMOTE oversampling or SVM prediction is missing. Please run previous cells.")

    # If inputs for SMOTE are available, proceed with SMOTE
    smote = SMOTE(random_state=42)
    X_train_resampled, y_train_resampled = smote.fit_resample(X_train_selected_scaled, y_train_selected)
    print("SMOTE oversampling re-completed. Resampled training data shape:")
    print(f"X_train_resampled: {X_train_resampled.shape}, y_train_resampled: {y_train_resampled.shape}")
    print(f"Resampled class distribution: {Counter(y_train_resampled)}")
else:
    print("Resampled training data (X_train_resampled, y_train_resampled) already available.")


# 1. 初始化 SVM 模型
#   - class_weight='balanced': 自動調整類別權重，以應對類別不平衡問題。
#   - kernel='rbf': 使用徑向基函數核 (Radial Basis Function kernel)，適用於非線性分類。
#   - random_state: 確保結果的可重現性。
svm_model = SVC(kernel='rbf', random_state=42, class_weight='balanced')
model_selected = svm_model


# 2. 訓練模型
print("開始訓練 Support Vector Machine (SVM) 模型...")
svm_model.fit(X_train_resampled, y_train_resampled) # 使用 SMOTE 過採樣後的數據進行訓練
print("模型訓練完成。")

# 3. 進行預測
y_pred_svm = svm_model.predict(X_test_selected_scaled)
y_pred_selected_svm = y_pred_selected = y_pred_svm
# y_pred_selected_svm = y_pred_selected


# '''
# 4. 評估模型性能
print("\n--- SVM 模型評估 ---")

# 準確度
accuracy_svm = accuracy_score(y_test_selected, y_pred_svm)
print(f"準確度 (Accuracy): {accuracy_svm:.4f}")

# 分類報告 (包含精確度、召回率、F1-score)
print("\n分類報告 (Classification Report):\n")
print(classification_report(y_test_selected, y_pred_svm))

# 混淆矩陣
print("\n混淆矩陣 (Confusion Matrix):\n")
cm_svm = confusion_matrix(y_test_selected, y_pred_svm, labels=svm_model.classes_)
display_cm_svm = ConfusionMatrixDisplay(confusion_matrix=cm_svm, display_labels=svm_model.classes_)
display_cm_svm.plot(cmap=plt.cm.Greens)
plt.title('Confusion Matrix for Support Vector Machine (SVM)')
plt.show()
# '''

"""## 評估模型性能"""

from sklearn.metrics import accuracy_score


# 5. 評估模型性能
print("\n--- 模型評估 (使用 X_selected) ---")

# 準確度
# accuracy_selected = accuracy_score(y_test_selected, y_pred_selected)
accuracy_selected_rf = accuracy_score(y_test_selected, y_pred_selected_rf)
accuracy_selected_lr = accuracy_score(y_test_selected, y_pred_selected_lr)
accuracy_selected_svm = accuracy_score(y_test_selected, y_pred_selected_svm)

# print(f"準確度 (Accuracy): {accuracy_selected:.4f}")
print(f"準確度 (rf Accuracy): {accuracy_selected_rf:.4f}")
print(f"準確度 (lr Accuracy): {accuracy_selected_lr:.4f}")
print(f"準確度 (svm Accuracy): {accuracy_selected_svm:.4f}")



# 分類報告 (包含精確度、召回率、F1-score)
# print("\n分類報告 (Classification Report):\n")
# print(classification_report(y_test_selected, y_pred_selected))
print("\n分類報告 (rf Classification Report):\n")
print(classification_report(y_test_selected, y_pred_selected_rf))

print("\n分類報告 (lr Classification Report):\n")
print(classification_report(y_test_selected, y_pred_selected_lr))

print("\n分類報告 (svm Classification Report):\n")
print(classification_report(y_test_selected, y_pred_selected_svm))




# 混淆矩陣
print("\n混淆矩陣 (Confusion Matrix):\n")
cm_selected = confusion_matrix(y_test_selected, y_pred_selected, labels=model_selected.classes_)
# cm_selected = confusion_matrix(y_test_selected, y_pred_selected, labels=model.classes_)

display_cm_selected = ConfusionMatrixDisplay(confusion_matrix=cm_selected, display_labels=model_selected.classes_)
# display_cm_selected = ConfusionMatrixDisplay(confusion_matrix=cm_selected, display_labels=model.classes_)
display_cm_selected.plot(cmap=plt.cm.Blues)
plt.title('Confusion Matrix for model_selected')
plt.show()

"""### 使用 SMOTE 過採樣資料重新訓練模型並加入 XGBoost
我們將使用 `X_train_resampled` 與 `y_train_resampled` 重新訓練模型，並評估它們在原始測試集 `X_test_selected_scaled` 上的表現。
"""

import pandas as pd
from sklearn.linear_model import LogisticRegression
from sklearn.ensemble import RandomForestClassifier
from sklearn.svm import SVC
from xgboost import XGBClassifier
from sklearn.metrics import classification_report, accuracy_score
from sklearn.preprocessing import LabelEncoder

# 1. 準備標籤編碼 (XGBoost 需要數值型標籤)
le = LabelEncoder()
y_train_resampled_encoded = le.fit_transform(y_train_resampled)
y_test_encoded = le.transform(y_test_selected)

# 2. 初始化模型
models = {
    'Logistic Regression': LogisticRegression(max_iter=5000, random_state=42),
    'Random Forest': RandomForestClassifier(n_estimators=200, max_depth=10, random_state=42),
    'SVM': SVC(kernel='rbf', random_state=42),
    'XGBoost': XGBClassifier(n_estimators=100, learning_rate=0.1, max_depth=6, random_state=42)
}

# 3. 訓練與評估
results = {}

print("--- 開始訓練模型 (使用 SMOTE 資料) ---")
for name, model in models.items():
    if name == 'XGBoost':
        model.fit(X_train_resampled, y_train_resampled_encoded)
        y_pred = model.predict(X_test_selected_scaled)
        # 轉回原始類別文字以便統一輸出報告
        y_pred_labels = le.inverse_transform(y_pred)
    else:
        model.fit(X_train_resampled, y_train_resampled)
        y_pred_labels = model.predict(X_test_selected_scaled)

    acc = accuracy_score(y_test_selected, y_pred_labels)
    results[name] = acc

    print(f"\n[ {name} ]")
    print(f"準確度 (Accuracy): {acc:.4f}")
    print(classification_report(y_test_selected, y_pred_labels))

print("\n--- 各模型準確度總結 ---")
for name, acc in results.items():
    print(f"{name}: {acc:.4f}")

"""### XGBoost 模型混淆矩陣分析
透過混淆矩陣，我們可以觀察模型在處理不平衡類別後的預測偏差情況。
"""

from sklearn.metrics import confusion_matrix, ConfusionMatrixDisplay
import matplotlib.pyplot as plt
from collections import Counter

# 驗證資料平衡狀態
print("--- 資料數量檢查 ---")
print(f"訓練集類別分佈 (SMOTE 後): {Counter(y_train_resampled)}")
print(f"測試集類別分佈 (原始比例): {Counter(y_test_selected)}")

# 取得 XGBoost 模型物件 (最新訓練的包含權重調整的模型)
xgb_model = models['XGBoost']

# 計算混淆矩陣
# 使用 le.classes_ 確保標籤順序一致
cm_xgb = confusion_matrix(y_test_selected, y_pred_labels, labels=le.classes_)

# 繪製圖形
fig, ax = plt.subplots(figsize=(8, 6))
display_cm_xgb = ConfusionMatrixDisplay(confusion_matrix=cm_xgb, display_labels=le.classes_)
display_cm_xgb.plot(cmap=plt.cm.Oranges, ax=ax)
plt.title('Confusion Matrix: XGBoost Evaluation on Imbalanced Test Set')
plt.show()

from sklearn.metrics import confusion_matrix, ConfusionMatrixDisplay
import matplotlib.pyplot as plt

# 1. 計算原始混淆矩陣與正規化矩陣
# normalize='true' 代表按真實標籤 (True Label) 的列總和進行正規化
cm_xgb = confusion_matrix(y_test_selected, y_pred_labels, labels=le.classes_)
cm_xgb_norm = confusion_matrix(y_test_selected, y_pred_labels, labels=le.classes_, normalize='true')

# 2. 繪製圖形
fig, ax = plt.subplots(1, 2, figsize=(16, 6))

# 左圖：絕對數值
disp_raw = ConfusionMatrixDisplay(confusion_matrix=cm_xgb, display_labels=le.classes_)
disp_raw.plot(cmap=plt.cm.Oranges, ax=ax[0])
ax[0].set_title('Confusion Matrix: Absolute Counts')

# 右圖：正規化比例
disp_norm = ConfusionMatrixDisplay(confusion_matrix=cm_xgb_norm, display_labels=le.classes_)
disp_norm.plot(cmap=plt.cm.Oranges, ax=ax[1], values_format='.2f')
ax[1].set_title('Confusion Matrix: Normalized (Recall)')

plt.tight_layout()
plt.show()

from sklearn.metrics import confusion_matrix, ConfusionMatrixDisplay
import matplotlib.pyplot as plt

# 1. 使用 XGBoost 對訓練集 (SMOTE 後) 進行預測
# 這裡使用已經編碼過的 y_train_resampled_encoded 作為真值
xgb_model = models['XGBoost']
y_train_pred_encoded = xgb_model.predict(X_train_resampled)

# 2. 計算訓練集混淆矩陣
# le.classes_ 包含 ['High', 'Low', 'Medium']，對應編碼後的 [0, 1, 2]
cm_train_xgb = confusion_matrix(y_train_resampled_encoded, y_train_pred_encoded)

# 3. 繪製圖形
fig, ax = plt.subplots(figsize=(8, 6))
display_cm_train = ConfusionMatrixDisplay(
    confusion_matrix=cm_train_xgb,
    display_labels=le.classes_
)

display_cm_train.plot(cmap=plt.cm.Blues, ax=ax)
plt.title('Confusion Matrix: XGBoost Evaluation on Balanced Training Set (SMOTE)')
plt.show()

# 額外印出各類別的準確統計
print("--- 訓練集預測數量統計 ---")
from collections import Counter
print(f"預測類別分佈: {Counter(le.inverse_transform(y_train_pred_encoded))}")

"""### XGBoost 特徵重要性分析
透過查看特徵重要性排行，我們可以找出影響供應商風險分類最關鍵的指標。
"""

# 1. 取得特徵重要性
# 使用已訓練好的 xgb_model (注意: 之前是在 models['XGBoost'] 或重訓練的 xgb_weighted)
# 這裡我們取最新訓練的 xgb_weighted 的特徵重要性
importances = xgb_weighted.feature_importances_
feature_names = X_train_selected.columns

# 2. 建立 DataFrame 排序
feature_importance_df = pd.DataFrame({
    'Feature': feature_names,
    'Importance': importances
}).sort_values(by='Importance', ascending=False)

# 3. 繪製圖表
plt.figure(figsize=(10, 8))
sns.barplot(x='Importance', y='Feature', data=feature_importance_df, palette='magma')
plt.title('XGBoost Feature Importance Ranking')
plt.xlabel('Importance Score')
plt.ylabel('Features')
plt.tight_layout()
plt.show()

# 列出前 10 大關鍵指標
print("前 10 大關鍵指標排行:")
print(feature_importance_df.head(10))

