# -*- coding: utf-8 -*-
"""Supplier Risk github.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1HU0U2eztxw7pPkYgaShlmbE-l09lpmtC

### `Load the CSV file into a DataFrame`
"""

import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns


from google.colab import drive
drive.mount('/content/drive')


# Load the CSV file into a DataFrame
# 手動掛接訓練CSV檔案
# df = pd.read_csv('/content/Data_中英欄位.csv')

df = pd.read_csv('/content/drive/MyDrive/Data_中英欄位.csv')
# df = pd.read_csv('/content/drive/MyDrive/Data_中英欄位_simplified.csv')
# df
display(df.shape)

# print("Displaying the first 10 rows of 'df' to verify column names:")
# display(df.head(10))

print('--- 檢查資料中的重複值 (Duplicates) ---')

# 檢查是否有重複的行
duplicates = df[df.duplicated()]

# 顯示重複的行數
print(f"資料中重複的行數: {len(duplicates)}")

# 如果有重複的行，顯示前幾行重複的資料
if not duplicates.empty:
    print("前幾行重複的資料:")
    display(duplicates.head())
else:
    print("資料中沒有重複的行。")

# 檢查 df 中的缺失值
print(df.isnull().sum())

# (可選) 顯示 df_train 中缺失值的百分比
print('\ndf 中缺失值的百分比:')
print((df.isnull().sum() / len(df)) * 100)

display(df.describe())

"""### 選取特徵X與目標變數Y 切分訓練/測試資料集"""

from sklearn.model_selection import train_test_split
import pandas as pd

# Define the target variable y
y = df['Supplier Risk（供應商風險等級）']


# Define the features X with only 'Supplier ESG Score（供應商ESG評分）' and 'PO Status（採購單狀態）'
X_selected = df[[
        'Supplier Tier（供應商層級）',
        'Maverick Spend（脫軌採購）',
        'Preferred Supplier（優先供應商）',
        'Days Late（延誤天數）',

        # bad feature importance
        'On Time Delivery（是否準時交貨）',
        'Invoice Status（發票狀態）',
        'Payment Status（付款狀態）',
        'Single Source Flag（單一來源標記）',
        'PO Type（採購單類型）',
        'Contract Type（合約類型）',
        'PO Status（採購單狀態）',

        # strong data leakage
        # 'Supplier ESG Score（供應商ESG評分）', # Removed due to strong data leakage with target variable
        ]]


# Handle categorical features in X_selected by one-hot encoding 'PO Status（採購單狀態）'
categorical_cols_selected = X_selected.select_dtypes(include='object').columns

if not categorical_cols_selected.empty:
    print(f"對以下類別特徵進行獨熱編碼: {list(categorical_cols_selected)}")
    X_selected = pd.get_dummies(X_selected, columns=categorical_cols_selected, drop_first=True)
else:
    print("沒有找到需要進行獨熱編碼的類別特徵。")

# Perform the train-test split (70% training, 30% testing)
# Using stratify=y to maintain the proportion of 'Supplier Risk' classes in both sets
X_train_selected, X_test_selected, y_train_selected, y_test_selected = train_test_split(
    X_selected, y, test_size=0.3, random_state=1, stratify=y
)

print(f"\n選取特徵後的 X 形狀: {X_selected.shape}")
print(f"目標變數 y 形狀: {y.shape}")

print(f"\n訓練特徵集 (X_train_selected) 形狀: {X_train_selected.shape}")
print(f"測試特徵集 (X_test_selected) 形狀: {X_test_selected.shape}")

print(f"訓練目標變數 (y_train_selected) 形狀: {y_train_selected.shape}")
print(f"測試目標變數 (y_test_selected) 形狀: {y_test_selected.shape}")

"""## 使用 `X_selected` 特徵縮放 (Feature Scaling) Standardization and Normalization"""

from sklearn.preprocessing import StandardScaler, MinMaxScaler
import pandas as pd


print("標準化和正規化前的訓練集形狀: ", X_train_selected.shape)
print("標準化和正規化前的測試集形狀: ", X_test_selected.shape)


print("--- 開始進行特徵標準化和正規化 ---")
# 1. 特徵標準化 (Standardization)
# 使用 StandardScaler 將特徵縮放到均值為0，標準差為1。
print("開始進行特徵標準化 (X_selected)...")
scaler_selected = StandardScaler()
X_train_selected_scaled = scaler_selected.fit_transform(X_train_selected)
X_test_selected_scaled = scaler_selected.transform(X_test_selected)

X_train_selected_std = scaler_selected.fit_transform(X_train_selected)
X_test_selected_std = scaler_selected.transform(X_test_selected)
print("特徵標準化完成。")




# 2. 特徵正規化 (Normalization)
# 在標準化後的數據上應用 MinMaxScaler，將數據縮放到0到1的範圍。
print("\n開始進行特徵正規化 (X_selected_std)...")
normalizer_selected = MinMaxScaler()
# X_train_selected_normalized = normalizer_selected.fit_transform(X_train_selected_scaled)
# X_test_selected_normalized = normalizer_selected.transform(X_test_selected_scaled)
X_train_selected_normalized = normalizer_selected.fit_transform(X_train_selected_std)
X_test_selected_normalized = normalizer_selected.transform(X_test_selected_std)
print("特徵正規化完成。")

print("標準化和正規化後的訓練集形狀: ", X_train_selected_normalized.shape)
print("標準化和正規化後的測試集形狀: ", X_test_selected_normalized.shape)

"""## 檢查類別不平衡 (Imbalanced Data) 並進行重複取樣 SMOTE（Synthetic Minority Over-sampling Technique，合成少數類別過採樣技術"""

print('--- 檢查類別不平衡 (Imbalanced Data) 並進行重複取樣 ---')

import pandas as pd
from collections import Counter
from imblearn.over_sampling import SMOTE
import matplotlib.pyplot as plt
import seaborn as sns

# 假設 X_train_selected_scaled 和 y_train_selected 已經在之前的單元格中定義。
# 如果尚未定義，請確保執行了特徵選擇和標準化的單元格。

print("原始訓練資料 (y_train_selected) 的類別分佈:")
original_counts = Counter(y_train_selected)
print(original_counts)

# 視覺化原始類別分佈
plt.figure(figsize=(8, 6))
sns.barplot(x=list(original_counts.keys()), y=list(original_counts.values()), palette='viridis')
plt.title('Original Training Data Class Distribution')
plt.xlabel('Supplier Risk Level')
plt.ylabel('Count')
plt.show()

# 初始化 SMOTE
# random_state 確保結果的可重現性
smote = SMOTE(random_state=42)

# 對訓練資料進行過採樣
X_train_resampled, y_train_resampled = smote.fit_resample(X_train_selected_scaled, y_train_selected)

print("\n過採樣後訓練資料的類別分佈:")
resampled_counts = Counter(y_train_resampled)
print(resampled_counts)

# 視覺化過採樣後類別分佈
plt.figure(figsize=(8, 6))
sns.barplot(x=list(resampled_counts.keys()), y=list(resampled_counts.values()), palette='viridis')
plt.title('Resampled Training Data Class Distribution (SMOTE)')
plt.xlabel('Supplier Risk Level')
plt.ylabel('Count')
plt.show()

print("\nSMOTE 過採樣完成。")
print(f"X_train_resampled 的形狀: {X_train_resampled.shape}")
print(f"y_train_resampled 的形狀: {y_train_resampled.shape}")

"""## 多類別分類模型（Multi-class Classification Model) 評估

### XGBoost Model （eXtreme Gradient Boosting)
"""

from sklearn.preprocessing import LabelEncoder
from xgboost import XGBClassifier
from sklearn.metrics import classification_report, accuracy_score, confusion_matrix, ConfusionMatrixDisplay
import matplotlib.pyplot as plt

# Prepare labels for XGBoost (XGBoost often prefers numerical labels for multi-class classification)
# Assuming y_train_resampled and y_test_selected are available from previous cells
le = LabelEncoder()
y_train_resampled_encoded = le.fit_transform(y_train_resampled)
y_test_encoded = le.transform(y_test_selected)

print("--- Training XGBoost Model ---")

# Initialize XGBoost Classifier
# Using parameters similar to the previous evaluation for consistency, or fine-tuned ones
xgb_model = XGBClassifier(
    n_estimators=100,
    learning_rate=0.1,
    max_depth=6,
    random_state=42,
    # For multi-class classification with LabelEncoder, use 'multi:softprob' or 'multi:softmax'
    # and num_class should be set to the number of unique classes
    objective='multi:softmax',
    num_class=len(le.classes_)
)


# Train the model using SMOTE resampled data
xgb_model.fit(X_train_resampled, y_train_resampled_encoded)
print("XGBoost model training complete.")

# Make predictions on the scaled test set
y_pred_encoded = xgb_model.predict(X_test_selected_scaled)

# Convert predictions back to original class labels for evaluation
y_pred_labels = le.inverse_transform(y_pred_encoded)



# Evaluate the model
print("\n--- XGBoost Model Evaluation ---")

accuracy = accuracy_score(y_test_selected, y_pred_labels)
print(f"準確度 (Accuracy): {accuracy:.4f}")

print("\n分類報告 (Classification Report):\n")
print(classification_report(y_test_selected, y_pred_labels))

print("\n混淆矩陣 (Confusion Matrix):\n")
cm = confusion_matrix(y_test_selected, y_pred_labels, labels=le.classes_)
display_cm = ConfusionMatrixDisplay(confusion_matrix=cm, display_labels=le.classes_)
display_cm.plot(cmap=plt.cm.YlOrRd)
plt.title('Confusion Matrix for XGBoost Classifier')
plt.show()

"""## 模型或變數存成 .pkl"""

import pickle

# 假設您的模型或資料變數名稱為 my_model
# 將 my_model 儲存為 model.pkl
'''
with open('/content/rf_model.pkl', 'wb') as f:
    pickle.dump(rf_model, f)

with open('/content/lr_model.pkl', 'wb') as f:
    pickle.dump(lr_model, f)

with open('/content/svm_model.pkl', 'wb') as f:
    pickle.dump(svm_model, f)
'''
with open('/content/xgb_model.pkl', 'wb') as f:
    pickle.dump(xgb_model, f)